# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'


target 'Rainy Shine' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '10.0'
  use_frameworks!

  # Pods for Rainy Shine
pod 'Alamofire', '~> 4.3'

end
